apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mmrf
  namespace: jrichter-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:1a705562e4888fc756c55e1c3e7928f3550f1ff52338339c36f78df2f04c1287
        name: my-nodejs
        resources: {}
status: {}
